/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opendatakit.suitcase.ui;

/**
 *
 * @author ADITYA N SAH
 */
public class TablePullPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public TablePullPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sTableId = new javax.swing.JComboBox<>();
        sDownloadAttachment = new javax.swing.JCheckBox();
        sApplyScanFmt = new javax.swing.JCheckBox();
        sExtraMetadata = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(471, 34));
        setName(""); // NOI18N

        sTableId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "geotagger", "exampleForm" }));

        sDownloadAttachment.setText("Attachments");

        sApplyScanFmt.setText("Scan-formatting");

        sExtraMetadata.setText("Metadata");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sTableId, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sDownloadAttachment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sApplyScanFmt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sExtraMetadata)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sTableId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDownloadAttachment)
                    .addComponent(sApplyScanFmt)
                    .addComponent(sExtraMetadata))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox sApplyScanFmt;
    private javax.swing.JCheckBox sDownloadAttachment;
    private javax.swing.JCheckBox sExtraMetadata;
    private javax.swing.JComboBox<String> sTableId;
    // End of variables declaration//GEN-END:variables
}
